#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumWeb.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLDIENDANCONGNGHE")]
	public partial class QLDIENDANCONGNGHEDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBaiGui(BaiGui instance);
    partial void UpdateBaiGui(BaiGui instance);
    partial void DeleteBaiGui(BaiGui instance);
    partial void InsertChuDe(ChuDe instance);
    partial void UpdateChuDe(ChuDe instance);
    partial void DeleteChuDe(ChuDe instance);
    partial void InsertCongDong(CongDong instance);
    partial void UpdateCongDong(CongDong instance);
    partial void DeleteCongDong(CongDong instance);
    partial void InsertLinhVuc(LinhVuc instance);
    partial void UpdateLinhVuc(LinhVuc instance);
    partial void DeleteLinhVuc(LinhVuc instance);
    partial void InsertNguoiSuDung(NguoiSuDung instance);
    partial void UpdateNguoiSuDung(NguoiSuDung instance);
    partial void DeleteNguoiSuDung(NguoiSuDung instance);
    partial void InsertAd(Ad instance);
    partial void UpdateAd(Ad instance);
    partial void DeleteAd(Ad instance);
    #endregion
		
		public QLDIENDANCONGNGHEDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLDIENDANCONGNGHEConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLDIENDANCONGNGHEDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDIENDANCONGNGHEDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDIENDANCONGNGHEDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDIENDANCONGNGHEDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BaiGui> BaiGuis
		{
			get
			{
				return this.GetTable<BaiGui>();
			}
		}
		
		public System.Data.Linq.Table<ChuDe> ChuDes
		{
			get
			{
				return this.GetTable<ChuDe>();
			}
		}
		
		public System.Data.Linq.Table<CongDong> CongDongs
		{
			get
			{
				return this.GetTable<CongDong>();
			}
		}
		
		public System.Data.Linq.Table<LinhVuc> LinhVucs
		{
			get
			{
				return this.GetTable<LinhVuc>();
			}
		}
		
		public System.Data.Linq.Table<NguoiSuDung> NguoiSuDungs
		{
			get
			{
				return this.GetTable<NguoiSuDung>();
			}
		}
		
		public System.Data.Linq.Table<Ad> Ads
		{
			get
			{
				return this.GetTable<Ad>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BaiGui")]
	public partial class BaiGui : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBaiGui;
		
		private int _MaChuDe;
		
		private int _MaCongDong;
		
		private int _MaLinhVuc;
		
		private int _MaNguoiSuDung;
		
		private System.DateTime _NgayGuiBai;
		
		private string _TenBai;
		
		private string _NoiDung;
		
		private System.Nullable<bool> _TinhTrang;
		
		private EntityRef<ChuDe> _ChuDe;
		
		private EntityRef<CongDong> _CongDong;
		
		private EntityRef<LinhVuc> _LinhVuc;
		
		private EntityRef<NguoiSuDung> _NguoiSuDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBaiGuiChanging(int value);
    partial void OnMaBaiGuiChanged();
    partial void OnMaChuDeChanging(int value);
    partial void OnMaChuDeChanged();
    partial void OnMaCongDongChanging(int value);
    partial void OnMaCongDongChanged();
    partial void OnMaLinhVucChanging(int value);
    partial void OnMaLinhVucChanged();
    partial void OnMaNguoiSuDungChanging(int value);
    partial void OnMaNguoiSuDungChanged();
    partial void OnNgayGuiBaiChanging(System.DateTime value);
    partial void OnNgayGuiBaiChanged();
    partial void OnTenBaiChanging(string value);
    partial void OnTenBaiChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnTinhTrangChanging(System.Nullable<bool> value);
    partial void OnTinhTrangChanged();
    #endregion
		
		public BaiGui()
		{
			this._ChuDe = default(EntityRef<ChuDe>);
			this._CongDong = default(EntityRef<CongDong>);
			this._LinhVuc = default(EntityRef<LinhVuc>);
			this._NguoiSuDung = default(EntityRef<NguoiSuDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBaiGui", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaBaiGui
		{
			get
			{
				return this._MaBaiGui;
			}
			set
			{
				if ((this._MaBaiGui != value))
				{
					this.OnMaBaiGuiChanging(value);
					this.SendPropertyChanging();
					this._MaBaiGui = value;
					this.SendPropertyChanged("MaBaiGui");
					this.OnMaBaiGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuDe", DbType="Int NOT NULL")]
		public int MaChuDe
		{
			get
			{
				return this._MaChuDe;
			}
			set
			{
				if ((this._MaChuDe != value))
				{
					if (this._ChuDe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChuDeChanging(value);
					this.SendPropertyChanging();
					this._MaChuDe = value;
					this.SendPropertyChanged("MaChuDe");
					this.OnMaChuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCongDong", DbType="Int NOT NULL")]
		public int MaCongDong
		{
			get
			{
				return this._MaCongDong;
			}
			set
			{
				if ((this._MaCongDong != value))
				{
					if (this._CongDong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCongDongChanging(value);
					this.SendPropertyChanging();
					this._MaCongDong = value;
					this.SendPropertyChanged("MaCongDong");
					this.OnMaCongDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLinhVuc", DbType="Int NOT NULL")]
		public int MaLinhVuc
		{
			get
			{
				return this._MaLinhVuc;
			}
			set
			{
				if ((this._MaLinhVuc != value))
				{
					if (this._LinhVuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLinhVucChanging(value);
					this.SendPropertyChanging();
					this._MaLinhVuc = value;
					this.SendPropertyChanged("MaLinhVuc");
					this.OnMaLinhVucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiSuDung", DbType="Int NOT NULL")]
		public int MaNguoiSuDung
		{
			get
			{
				return this._MaNguoiSuDung;
			}
			set
			{
				if ((this._MaNguoiSuDung != value))
				{
					if (this._NguoiSuDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguoiSuDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiSuDung = value;
					this.SendPropertyChanged("MaNguoiSuDung");
					this.OnMaNguoiSuDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGuiBai", DbType="DateTime NOT NULL")]
		public System.DateTime NgayGuiBai
		{
			get
			{
				return this._NgayGuiBai;
			}
			set
			{
				if ((this._NgayGuiBai != value))
				{
					this.OnNgayGuiBaiChanging(value);
					this.SendPropertyChanging();
					this._NgayGuiBai = value;
					this.SendPropertyChanged("NgayGuiBai");
					this.OnNgayGuiBaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBai", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TenBai
		{
			get
			{
				return this._TenBai;
			}
			set
			{
				if ((this._TenBai != value))
				{
					this.OnTenBaiChanging(value);
					this.SendPropertyChanging();
					this._TenBai = value;
					this.SendPropertyChanged("TenBai");
					this.OnTenBaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Bit")]
		public System.Nullable<bool> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuDe_BaiGui", Storage="_ChuDe", ThisKey="MaChuDe", OtherKey="MaChuDe", IsForeignKey=true)]
		public ChuDe ChuDe
		{
			get
			{
				return this._ChuDe.Entity;
			}
			set
			{
				ChuDe previousValue = this._ChuDe.Entity;
				if (((previousValue != value) 
							|| (this._ChuDe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChuDe.Entity = null;
						previousValue.BaiGuis.Remove(this);
					}
					this._ChuDe.Entity = value;
					if ((value != null))
					{
						value.BaiGuis.Add(this);
						this._MaChuDe = value.MaChuDe;
					}
					else
					{
						this._MaChuDe = default(int);
					}
					this.SendPropertyChanged("ChuDe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongDong_BaiGui", Storage="_CongDong", ThisKey="MaCongDong", OtherKey="MaCongDong", IsForeignKey=true)]
		public CongDong CongDong
		{
			get
			{
				return this._CongDong.Entity;
			}
			set
			{
				CongDong previousValue = this._CongDong.Entity;
				if (((previousValue != value) 
							|| (this._CongDong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CongDong.Entity = null;
						previousValue.BaiGuis.Remove(this);
					}
					this._CongDong.Entity = value;
					if ((value != null))
					{
						value.BaiGuis.Add(this);
						this._MaCongDong = value.MaCongDong;
					}
					else
					{
						this._MaCongDong = default(int);
					}
					this.SendPropertyChanged("CongDong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LinhVuc_BaiGui", Storage="_LinhVuc", ThisKey="MaLinhVuc", OtherKey="MaLinhVuc", IsForeignKey=true)]
		public LinhVuc LinhVuc
		{
			get
			{
				return this._LinhVuc.Entity;
			}
			set
			{
				LinhVuc previousValue = this._LinhVuc.Entity;
				if (((previousValue != value) 
							|| (this._LinhVuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LinhVuc.Entity = null;
						previousValue.BaiGuis.Remove(this);
					}
					this._LinhVuc.Entity = value;
					if ((value != null))
					{
						value.BaiGuis.Add(this);
						this._MaLinhVuc = value.MaLinhVuc;
					}
					else
					{
						this._MaLinhVuc = default(int);
					}
					this.SendPropertyChanged("LinhVuc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiSuDung_BaiGui", Storage="_NguoiSuDung", ThisKey="MaNguoiSuDung", OtherKey="MaNguoiSuDung", IsForeignKey=true)]
		public NguoiSuDung NguoiSuDung
		{
			get
			{
				return this._NguoiSuDung.Entity;
			}
			set
			{
				NguoiSuDung previousValue = this._NguoiSuDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiSuDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiSuDung.Entity = null;
						previousValue.BaiGuis.Remove(this);
					}
					this._NguoiSuDung.Entity = value;
					if ((value != null))
					{
						value.BaiGuis.Add(this);
						this._MaNguoiSuDung = value.MaNguoiSuDung;
					}
					else
					{
						this._MaNguoiSuDung = default(int);
					}
					this.SendPropertyChanged("NguoiSuDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChuDe")]
	public partial class ChuDe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaChuDe;
		
		private string _TenChuDe;
		
		private EntitySet<BaiGui> _BaiGuis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChuDeChanging(int value);
    partial void OnMaChuDeChanged();
    partial void OnTenChuDeChanging(string value);
    partial void OnTenChuDeChanged();
    #endregion
		
		public ChuDe()
		{
			this._BaiGuis = new EntitySet<BaiGui>(new Action<BaiGui>(this.attach_BaiGuis), new Action<BaiGui>(this.detach_BaiGuis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuDe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaChuDe
		{
			get
			{
				return this._MaChuDe;
			}
			set
			{
				if ((this._MaChuDe != value))
				{
					this.OnMaChuDeChanging(value);
					this.SendPropertyChanging();
					this._MaChuDe = value;
					this.SendPropertyChanged("MaChuDe");
					this.OnMaChuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChuDe", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenChuDe
		{
			get
			{
				return this._TenChuDe;
			}
			set
			{
				if ((this._TenChuDe != value))
				{
					this.OnTenChuDeChanging(value);
					this.SendPropertyChanging();
					this._TenChuDe = value;
					this.SendPropertyChanged("TenChuDe");
					this.OnTenChuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuDe_BaiGui", Storage="_BaiGuis", ThisKey="MaChuDe", OtherKey="MaChuDe")]
		public EntitySet<BaiGui> BaiGuis
		{
			get
			{
				return this._BaiGuis;
			}
			set
			{
				this._BaiGuis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BaiGuis(BaiGui entity)
		{
			this.SendPropertyChanging();
			entity.ChuDe = this;
		}
		
		private void detach_BaiGuis(BaiGui entity)
		{
			this.SendPropertyChanging();
			entity.ChuDe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CongDong")]
	public partial class CongDong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCongDong;
		
		private string _TenCongDong;
		
		private EntitySet<BaiGui> _BaiGuis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCongDongChanging(int value);
    partial void OnMaCongDongChanged();
    partial void OnTenCongDongChanging(string value);
    partial void OnTenCongDongChanged();
    #endregion
		
		public CongDong()
		{
			this._BaiGuis = new EntitySet<BaiGui>(new Action<BaiGui>(this.attach_BaiGuis), new Action<BaiGui>(this.detach_BaiGuis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCongDong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaCongDong
		{
			get
			{
				return this._MaCongDong;
			}
			set
			{
				if ((this._MaCongDong != value))
				{
					this.OnMaCongDongChanging(value);
					this.SendPropertyChanging();
					this._MaCongDong = value;
					this.SendPropertyChanged("MaCongDong");
					this.OnMaCongDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCongDong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenCongDong
		{
			get
			{
				return this._TenCongDong;
			}
			set
			{
				if ((this._TenCongDong != value))
				{
					this.OnTenCongDongChanging(value);
					this.SendPropertyChanging();
					this._TenCongDong = value;
					this.SendPropertyChanged("TenCongDong");
					this.OnTenCongDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongDong_BaiGui", Storage="_BaiGuis", ThisKey="MaCongDong", OtherKey="MaCongDong")]
		public EntitySet<BaiGui> BaiGuis
		{
			get
			{
				return this._BaiGuis;
			}
			set
			{
				this._BaiGuis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BaiGuis(BaiGui entity)
		{
			this.SendPropertyChanging();
			entity.CongDong = this;
		}
		
		private void detach_BaiGuis(BaiGui entity)
		{
			this.SendPropertyChanging();
			entity.CongDong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LinhVuc")]
	public partial class LinhVuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLinhVuc;
		
		private string _TenLinhVuc;
		
		private EntitySet<BaiGui> _BaiGuis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLinhVucChanging(int value);
    partial void OnMaLinhVucChanged();
    partial void OnTenLinhVucChanging(string value);
    partial void OnTenLinhVucChanged();
    #endregion
		
		public LinhVuc()
		{
			this._BaiGuis = new EntitySet<BaiGui>(new Action<BaiGui>(this.attach_BaiGuis), new Action<BaiGui>(this.detach_BaiGuis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLinhVuc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLinhVuc
		{
			get
			{
				return this._MaLinhVuc;
			}
			set
			{
				if ((this._MaLinhVuc != value))
				{
					this.OnMaLinhVucChanging(value);
					this.SendPropertyChanging();
					this._MaLinhVuc = value;
					this.SendPropertyChanged("MaLinhVuc");
					this.OnMaLinhVucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLinhVuc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenLinhVuc
		{
			get
			{
				return this._TenLinhVuc;
			}
			set
			{
				if ((this._TenLinhVuc != value))
				{
					this.OnTenLinhVucChanging(value);
					this.SendPropertyChanging();
					this._TenLinhVuc = value;
					this.SendPropertyChanged("TenLinhVuc");
					this.OnTenLinhVucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LinhVuc_BaiGui", Storage="_BaiGuis", ThisKey="MaLinhVuc", OtherKey="MaLinhVuc")]
		public EntitySet<BaiGui> BaiGuis
		{
			get
			{
				return this._BaiGuis;
			}
			set
			{
				this._BaiGuis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BaiGuis(BaiGui entity)
		{
			this.SendPropertyChanging();
			entity.LinhVuc = this;
		}
		
		private void detach_BaiGuis(BaiGui entity)
		{
			this.SendPropertyChanging();
			entity.LinhVuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiSuDung")]
	public partial class NguoiSuDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNguoiSuDung;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _HoTen;
		
		private string _DiaChi;
		
		private string _GioiTinh;
		
		private System.DateTime _NgaySinh;
		
		private string _SoDienThoai;
		
		private string _Email;
		
		private EntitySet<BaiGui> _BaiGuis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguoiSuDungChanging(int value);
    partial void OnMaNguoiSuDungChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public NguoiSuDung()
		{
			this._BaiGuis = new EntitySet<BaiGui>(new Action<BaiGui>(this.attach_BaiGuis), new Action<BaiGui>(this.detach_BaiGuis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiSuDung", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNguoiSuDung
		{
			get
			{
				return this._MaNguoiSuDung;
			}
			set
			{
				if ((this._MaNguoiSuDung != value))
				{
					this.OnMaNguoiSuDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiSuDung = value;
					this.SendPropertyChanged("MaNguoiSuDung");
					this.OnMaNguoiSuDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(10)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiSuDung_BaiGui", Storage="_BaiGuis", ThisKey="MaNguoiSuDung", OtherKey="MaNguoiSuDung")]
		public EntitySet<BaiGui> BaiGuis
		{
			get
			{
				return this._BaiGuis;
			}
			set
			{
				this._BaiGuis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BaiGuis(BaiGui entity)
		{
			this.SendPropertyChanging();
			entity.NguoiSuDung = this;
		}
		
		private void detach_BaiGuis(BaiGui entity)
		{
			this.SendPropertyChanging();
			entity.NguoiSuDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ad")]
	public partial class Ad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaAdmin;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaAdminChanging(int value);
    partial void OnMaAdminChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public Ad()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaAdmin", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaAdmin
		{
			get
			{
				return this._MaAdmin;
			}
			set
			{
				if ((this._MaAdmin != value))
				{
					this.OnMaAdminChanging(value);
					this.SendPropertyChanging();
					this._MaAdmin = value;
					this.SendPropertyChanged("MaAdmin");
					this.OnMaAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
